# Generated by Django 5.1.2 on 2024-11-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_userpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='stripe_checkout_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
