# Generated by Django 5.1.2 on 2024-12-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_order_amount_paid_alter_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadd',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='shippingadd',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='shippingadd',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingadd',
            name='code',
        ),
        migrations.RemoveField(
            model_name='shippingadd',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingadd',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shippingadd',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='shippingadd',
            name='province',
        ),
    ]
