# Generated by Django 5.1.2 on 2024-12-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_shippingadd_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadd',
            name='address1',
            field=models.CharField(default='123 Main Street', max_length=250),
        ),
        migrations.AddField(
            model_name='shippingadd',
            name='address2',
            field=models.CharField(default='Apt 101', max_length=250),
        ),
        migrations.AddField(
            model_name='shippingadd',
            name='city',
            field=models.CharField(default='New York', max_length=250),
        ),
        migrations.AddField(
            model_name='shippingadd',
            name='code',
            field=models.CharField(default='10001', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingadd',
            name='country',
            field=models.CharField(blank=True, default='USA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingadd',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingadd',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingadd',
            name='province',
            field=models.CharField(blank=True, default='New York', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_Address',
            field=models.TextField(default='123 Main Street, Apt 101, New York, USA', max_length=5500),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='stripe_checkout_id',
            field=models.CharField(default='default_checkout_id', max_length=255, unique=True),
        ),
    ]
