# Generated by Django 5.1.2 on 2024-11-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_catergory_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel',
            field=models.CharField(blank=True, default='Not Specified', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='Unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='No Warranty', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, default='Not Specified', max_length=20),
        ),
    ]
