# Generated by Django 5.1.2 on 2024-11-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_product_dimensions_product_fuel_product_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fuel',
            field=models.CharField(blank=True, default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='Not Specified', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='No Warranty', max_length=20),
        ),
    ]
