# Generated by Django 5.1.2 on 2024-12-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_product_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
