# Generated by Django 5.1.2 on 2024-12-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_remove_product_catergory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='fuel',
            field=models.CharField(blank=True, default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='Not Specified', max_length=20),
        ),
    ]
