# Generated by Django 5.1.2 on 2024-12-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_product_fuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
