# Generated by Django 5.1.2 on 2024-12-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_product_dimensions_product_fuel_product_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
